# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: false
warnings_are_errors: false
r_check_args: "--no-manual --as--cran --no-vignettes"
r_build_args: "--no-build-vignettes"
cache: packages

r_packages:
  - covr
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
